DROP DATABASE IF EXISTS dndne_db;
CREATE DATABASE dndne_db OWNER admin;
CREATE USER admin WITH PASSWORD 'admin';
GRANT ALL PRIVILEGES ON DATABASE dndne_db TO admin;

CREATE TYPE "character_classes" AS ENUM (
  'Barbarian',
  'Wizard',
  'Bard'
);

CREATE TYPE "item_type" AS ENUM (
  'weapon',
  'armor',
  'potion'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" text NOT NULL,
  "email" text UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "characters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "name" text,
  "class" character_classes,
  "level" integer,
  "xp" integer,
  "strength" integer,
  "dexterity" integer,
  "constitution" integer,
  "intelligence" integer,
  "wisdom" integer,
  "charisma" integer,
  "created_at" timestamp
);

CREATE TABLE "exercises" (
  "id" integer PRIMARY KEY,
  "name" text,
  "category" text,
  "difficulty" integer,
  "xp_reward" integer
);

CREATE TABLE "quests" (
  "id" integer PRIMARY KEY,
  "name" text,
  "description" text,
  "exercise_id" integer,
  "amount" integer,
  "xp_reward" integer,
  "item_reward" integer
);

CREATE TABLE "workout_logs" (
  "id" integer PRIMARY KEY,
  "user_id" integer,
  "exercise_id" integer,
  "amount" integer,
  "date" timestamp
);

CREATE TABLE "items" (
  "id" integer PRIMARY KEY,
  "name" text,
  "description" text,
  "type" item_type
);

CREATE TABLE "item_effect" (
  "id" integer PRIMARY KEY,
  "item_id" int,
  "attribute" text,
  "operation" text,
  "value" int,
  "duration" int
);

CREATE TABLE "inventory" (
  "id" integer PRIMARY KEY,
  "item_id" integer,
  "user_id" integer,
  "quantity" integer
);

ALTER TABLE "characters" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "quests" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "quests" ADD FOREIGN KEY ("item_reward") REFERENCES "items" ("id");

ALTER TABLE "workout_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workout_logs" ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "item_effect" ADD FOREIGN KEY ("item_id") REFERENCES "items" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("item_id") REFERENCES "items" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
